name: Main
on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        default: dev
        options:
          - dev
          - stage
          - prod
          - preprod
          - uat
        description: Environment to deploy onto
jobs:
  Development:
    if: ${{ github.event.inputs.Environment == 'dev' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: dev
      
    defaults:
      run:
        working-directory: app01
    steps:
      - id: checkOutRepository
        name: Checkout Repository
        uses: actions/checkout@v4
      