name: Github Action Tutorials
on:
  push:
    branches:
      - master
      - main
jobs:
  Development:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app01
    steps:
      - id: "A"
        name: Checkout Repository
        uses: actions/checkout@v4
      - id: "Github"
        name: Context tutorials
        env:
          CUSTOM_GITHUB: ${{ toJson(github) }}
        run: echo $CUSTOM_GITHUB
      - id: "Job"
        name: Context tutorials
        env:
          CUSTOM_GITHUB: ${{ toJson(job) }}
        run: echo $CUSTOM_GITHUB
      - id: "Steps"
        name: Context tutorials
        env:
          CUSTOM_GITHUB: ${{ toJson(steps) }}
        run: echo $CUSTOM_GITHUB
      - id: "Runner"
        name: Context tutorials
        env:
          CUSTOM_GITHUB: ${{ toJson(runner) }}
        run: echo $CUSTOM_GITHUB

